-- MySQL Script generated by MySQL Workbench
-- Fri Feb  5 20:12:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema testing
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `testing` DEFAULT CHARACTER SET utf8 ;
USE `testing` ;

CREATE TABLE `answer` (
                          `id` int NOT NULL AUTO_INCREMENT,
                          `answer_ua` varchar(255) DEFAULT NULL,
                          `answer_en` varchar(255) DEFAULT NULL,
                          `correct` tinyint(1) DEFAULT NULL,
                          `question_id` int NOT NULL,
                          PRIMARY KEY (`id`),
                          KEY `fk_answer_question1_idx` (`question_id`),
                          CONSTRAINT `fk_answer_question1` FOREIGN KEY (`question_id`) REFERENCES `question` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8;

CREATE TABLE `question` (
                            `id` int NOT NULL AUTO_INCREMENT,
                            `question_ua` varchar(255) DEFAULT NULL,
                            `question_en` varchar(255) DEFAULT NULL,
                            `test_id` int NOT NULL,
                            PRIMARY KEY (`id`),
                            KEY `fk_question_test1_idx` (`test_id`),
                            CONSTRAINT `fk_question_test1` FOREIGN KEY (`test_id`) REFERENCES `test` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

CREATE TABLE `role` (
                        `id` int NOT NULL,
                        `role` enum('ADMIN','STUDENT') DEFAULT NULL,
                        PRIMARY KEY (`id`),
                        UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `subject` (
                           `id` int NOT NULL AUTO_INCREMENT,
                           `name_ua` varchar(255) DEFAULT NULL,
                           `name_en` varchar(255) DEFAULT NULL,
                           `description_ua` varchar(255) DEFAULT NULL,
                           `description_en` varchar(255) DEFAULT NULL,
                           `admin_id` int NOT NULL,
                           `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `name_UNIQUE` (`name_ua`),
                           UNIQUE KEY `name_en_UNIQUE` (`name_en`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;

CREATE TABLE `subject_has_test` (
                                    `subject_id` int NOT NULL,
                                    `test_id` int NOT NULL,
                                    PRIMARY KEY (`subject_id`,`test_id`),
                                    KEY `fk_subject_has_test_test1_idx` (`test_id`),
                                    KEY `fk_subject_has_test_subject1_idx` (`subject_id`),
                                    CONSTRAINT `fk_subject_has_test_subject1` FOREIGN KEY (`subject_id`) REFERENCES `subject` (`id`),
                                    CONSTRAINT `fk_subject_has_test_test1` FOREIGN KEY (`test_id`) REFERENCES `test` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `test` (
                        `id` int NOT NULL AUTO_INCREMENT,
                        `name_ua` varchar(255) NOT NULL,
                        `name_en` varchar(255) NOT NULL,
                        `complexity` int DEFAULT NULL,
                        `requests_quantity` int DEFAULT NULL,
                        `blocked` tinyint(1) NOT NULL,
                        `timer` int NOT NULL,
                        `description_ua` varchar(255) DEFAULT NULL,
                        `description_en` varchar(255) DEFAULT NULL,
                        `subject_id` int DEFAULT NULL,
                        `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                        PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

CREATE TABLE `test_result` (
                               `id` int NOT NULL AUTO_INCREMENT,
                               `result` int DEFAULT NULL,
                               `user_id` int NOT NULL,
                               `test_id` int NOT NULL,
                               `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                               PRIMARY KEY (`id`),
                               KEY `fk_test_results_user1_idx` (`user_id`),
                               KEY `fk_test_results_test1_idx` (`test_id`),
                               CONSTRAINT `fk_test_results_test1` FOREIGN KEY (`test_id`) REFERENCES `test` (`id`),
                               CONSTRAINT `fk_test_results_user1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=utf8;

CREATE TABLE `user` (
                        `id` int NOT NULL AUTO_INCREMENT,
                        `login` varchar(45) NOT NULL,
                        `name` varchar(45) DEFAULT NULL,
                        `surname` varchar(45) DEFAULT NULL,
                        `email` varchar(45) DEFAULT NULL,
                        `password` varchar(255) DEFAULT NULL,
                        `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                        `blocked` tinyint(1) DEFAULT NULL,
                        `role_id` int NOT NULL,
                        PRIMARY KEY (`id`),
                        UNIQUE KEY `login_UNIQUE` (`login`),
                        KEY `fk_user_role1_idx` (`role_id`),
                        CONSTRAINT `fk_user_role1` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
