-- MySQL Script generated by MySQL Workbench
-- Fri Feb  5 20:12:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema testing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testing` DEFAULT CHARACTER SET utf8 ;
USE `testing` ;

-- -----------------------------------------------------
-- Table `testing`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testing`.`role` (
  `id` INT NOT NULL,
  `role` ENUM('ADMIN', 'STUDENT') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testing`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testing`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `blocked` TINYINT(1) NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `testing`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testing`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testing`.`test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_ua` VARCHAR(255) NOT NULL,
  `name_en` VARCHAR(255) NOT NULL,
  `complexity` INT NULL,
  `requests_quantity` INT NULL,
  `blocked` TINYINT(1) NOT NULL,
  `timer` INT NOT NULL,
  `description_ua` VARCHAR(255) NULL,
  `description_en` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `subject_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `subject_id_UNIQUE` (`subject_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testing`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testing`.`question` (
  `id` INT NOT NULL,
  `question_ua` VARCHAR(255) NULL,
  `question_en` VARCHAR(255) NULL,
  `test_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_test1_idx` (`test_id` ASC) VISIBLE,
  CONSTRAINT `fk_question_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `testing`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testing`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testing`.`answer` (
  `id` INT NOT NULL,
  `answer_ua` VARCHAR(255) NULL,
  `answer_en` VARCHAR(255) NULL,
  `correct` TINYINT(1) NULL,
  `question_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_answer_question1_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `testing`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testing`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testing`.`subject` (
  `id` INT NOT NULL,
  `name_ua` VARCHAR(255) NULL,
  `name_en` VARCHAR(255) NULL,
  `description_ua` VARCHAR(255) NULL,
  `description_en` VARCHAR(255) NULL,
  `admin_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name_ua` ASC) VISIBLE,
  UNIQUE INDEX `name_en_UNIQUE` (`name_en` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testing`.`subject_has_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testing`.`subject_has_test` (
  `subject_id` INT NOT NULL,
  `test_id` INT NOT NULL,
  PRIMARY KEY (`subject_id`, `test_id`),
  INDEX `fk_subject_has_test_test1_idx` (`test_id` ASC) VISIBLE,
  INDEX `fk_subject_has_test_subject1_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_subject_has_test_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `testing`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subject_has_test_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `testing`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testing`.`test_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testing`.`test_results` (
  `id` INT NOT NULL,
  `result` INT NULL,
  `user_id` INT NOT NULL,
  `test_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_test_results_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_test_results_test1_idx` (`test_id` ASC) VISIBLE,
  CONSTRAINT `fk_test_results_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `testing`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_results_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `testing`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
